import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import Map from "./components/Map";
import Header from "./components/Header";

import { useImmer } from "use-immer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [markers, setMarkers] = useImmer<mapit.Marker[]>([]);
  const [options, setOptions] = useImmer<google.maps.MapOptions>({
    zoom: 2,
    zoomControl: false,
    minZoom: 2,
    maxZoom: 16,
    streetViewControl: false,
    mapTypeControl: false,
    fullscreenControl: false,
    zoomControlOptions: {
      position: 9,
    },
    styles: [],
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header options={options} setOptions={setOptions} markers={markers} setMarkers={setMarkers} />
        <Map options={options} setOptions={setOptions} markers={markers} setMarkers={setMarkers} />
      </main>
    </>
  );
}
